name:                mqtt-bridge
version:             0.1.0.0
github:              "dustin/mqtt-bridge"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/mqtt-bridge#readme>

dependencies:
- base >= 4.7 && < 5
- stm
- optparse-applicative
- megaparsec
- text
- net-mqtt
- unordered-containers
- async
- bytestring
- network-uri
- utf8-string
- containers
- hslogger
- ekg
- ekg-core

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  mqtt-bridge:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - mqtt-bridge
